import cv2
from ultralytics import YOLO
import time
import os
from datetime import datetime
import smtplib
from email.message import EmailMessage

# ---------- EMAIL SETTINGS ----------
EMAIL_SENDER = "ahmadsyedharoon@gmail.com"
EMAIL_PASSWORD = "ztvt bwsm asbg kixn"
EMAIL_RECEIVER = "dipornodip@gmail.com"
# ------------------------------------

# ---------------------- USER INPUT ----------------------

# Ask user for camera source
try:
    source_input = int(input("Enter camera source (e.g., 0, 1, 2): "))
except ValueError:
    print("Invalid input. Defaulting to camera 0.")
    source_input = 0

# Ask user whether to save data
save_choice = input("Save detection data? (yes / no): ").strip().lower()
SAVE_DATA = save_choice in ["yes", "y"]

print(f"\nCamera Source: {source_input}")
print(f"Save Data: {SAVE_DATA}\n")

# ---------------------- EMAIL ALERT FUNCTION ----------------------
def send_email_alert(image_path, item):

    msg = EmailMessage()
    msg["Subject"] = f"⚠️ Security Alert — Human Carrying {item}"
    msg["From"] = EMAIL_SENDER
    msg["To"] = EMAIL_RECEIVER

    msg.set_content(
        f"""
Security Event Detected

Detected object: {item}
Event type: Human confirmed carrying dangerous object

Snapshot image is attached.

This alert was generated by the Nazar Vision System.
"""
    )

    # Attach image
    with open(image_path, "rb") as f:
        img_data = f.read()

    msg.add_attachment(
        img_data,
        maintype="image",
        subtype="jpeg",
        filename="alert_snapshot.jpg"
    )

    # Send email via Gmail SMTP
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(EMAIL_SENDER, EMAIL_PASSWORD)
        smtp.send_message(msg)

    print("📧 Email alert sent successfully")

# ---------------------- GATE 1 ----------------------
    
def gate_1(source, model, conf_threshold):
    global gate1_bool, item
    
    item = None
    cap = cv2.VideoCapture(source)

    THINNESS_THRESHOLD = 0.3   # Adjust 0.2–0.4 depending on strictness

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame, verbose=False)
        detected = 0

        for result in results:
            for box in result.boxes:
                confidence = float(box.conf)
                class_id = int(box.cls)
                class_name = model.names[class_id].lower()

                if confidence < conf_threshold:
                    continue

                # ---------------- KNIFE SHAPE CHECK ----------------
                if class_name == "knife":

                    x1, y1, x2, y2 = map(float, box.xyxy[0])
                    width = x2 - x1
                    height = y2 - y1

                    if width <= 0 or height <= 0:
                        continue

                    # Orientation-independent thinness ratio
                    thinness_ratio = min(width, height) / max(width, height)

                    print(f"Knife detected — Thinness ratio: {thinness_ratio:.2f}")

                    if thinness_ratio >= THINNESS_THRESHOLD:
                        print("Knife rejected — shape not thin enough")
                        continue  # Reject this detection

                    print("Knife accepted — shape valid")
                    item = "knife"

                elif class_name == "alcohol":
                    item = "alcohol"

                detected = 1
                print(f"Detected: {class_name} ({confidence:.2f})")
                gate1_bool = True
                cap.release()
                return True

        if detected == 0:
            print(0)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    return False



# ---------------------- GATE 2 ----------------------

def gate_2(source, model, conf_threshold):

    cap = cv2.VideoCapture(source)
    start_time = None

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame, verbose=False)

        person_detected = False
        for result in results:
            for box in result.boxes:
                confidence = float(box.conf)
                cls = int(box.cls)

                if cls == 0 and confidence > conf_threshold:
                    person_detected = True
                    break

        if person_detected:
            if start_time is None:
                start_time = time.time()
            elif time.time() - start_time >= 1:
                print("Person also detected")
                return True
        else:
            return False

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    return False


# ---------------------- SAVE EVENT ----------------------

def notif():
    global item

    if not SAVE_DATA:
        print("⚠ Data saving disabled — skipping log & snapshot.")
        return

    cap = cv2.VideoCapture(source_input)
    ret, frame = cap.read()

    print(f"Human with {item} in possession")

    now = datetime.now()
    timestamp = now.strftime("%Y%m%d_%H%M%S")

    folder1_path = r"C:\Users\ahmad\Nazar\instances"
    folder2_path = r"C:\Users\ahmad\Nazar\instance_logs"

    os.makedirs(folder1_path, exist_ok=True)
    os.makedirs(folder2_path, exist_ok=True)

    image_path = os.path.join(folder1_path, f"danger_instance_{timestamp}.jpg")
    cv2.imwrite(image_path, frame)

    log_path = os.path.join(folder2_path, f"danger_instance_{timestamp}.txt")
    with open(log_path, 'w') as log_file:
        log_file.write(f"Detected human with {item} at {now}\n")

    print(f"Image saved: {image_path}")
    print(f"Log saved:   {log_path}")
    send_email_alert(image_path, item)

# ---------------------- MODELS ----------------------

model_1 = YOLO('Nazar_17.pt')
model_1.overrides['verbose'] = False

model_2 = YOLO('yolo11n.pt')
model_2.overrides['verbose'] = False

conf_threshold_1 = 0.65
conf_threshold_2 = 0.7


# ---------------------- MAIN LOOP ----------------------

while True:
    gate1_bool = False

    while not gate1_bool:
        gate1_bool = gate_1(source_input, model_1, conf_threshold_1)

    if gate1_bool and gate_2(source_input, model_2, conf_threshold_2):
        notif()
    else:
        print(f"{item} found, no Human")
